#! /bin/sh

if [ "$#" -ne 1 ]                                            
then                                                         
echo "Invalid command. Usage : $0 input.xml >> output.html"  
exit -1                                                      
fi                                                           

/usr/lib/pvx/java/xml/runxsl -XSL /usr/lib/pvx/www_interface/broker-xml2html.xsl -IN $1
