var xmlGlossary1Data = "";
xmlGlossary1Data += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlGlossary1Data += '<html xmlns:MadCap=\"http://www.madcapsoftware.com/Schemas/MadCap.xsd\" MadCap:tocPath=\"\" MadCap:InPreviewMode=\"false\" MadCap:PreloadImages=\"false\" MadCap:RuntimeFileType=\"Glossary\" MadCap:TargetType=\"WebHelp\" lang=\"en-us\" xml:lang=\"en-us\" MadCap:PathToHelpSystem=\"../\" MadCap:HelpSystemFileName=\"Bank Rec.xml\">';
xmlGlossary1Data += '    <!-- saved from url=(0016)http://localhost -->';
xmlGlossary1Data += '    <head>';
xmlGlossary1Data += '        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />';
xmlGlossary1Data += '        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />';
xmlGlossary1Data += '        <link href=\"SkinSupport/Slideshow.css\" rel=\"stylesheet\" type=\"text/css\" MadCap:generated=\"True\" />';
xmlGlossary1Data += '        <link href=\"SkinSupport/MadCap.css\" rel=\"stylesheet\" type=\"text/css\" MadCap:generated=\"True\" />';
xmlGlossary1Data += '        <title>Glossary</title>';
xmlGlossary1Data += '        <link href=\"Resources/Stylesheets/Styles.css\" rel=\"stylesheet\" type=\"text/css\" />';
xmlGlossary1Data += '        <script src=\"SkinSupport/jquery.min.js\" type=\"text/javascript\">';
xmlGlossary1Data += '        </script>';
xmlGlossary1Data += '        <script src=\"SkinSupport/MadCapAll.js\" type=\"text/javascript\">';
xmlGlossary1Data += '        </script>';
xmlGlossary1Data += '        <script src=\"SkinSupport/MadCapTopicAll.js\" type=\"text/javascript\">';
xmlGlossary1Data += '        </script>';
xmlGlossary1Data += '    </head>';
xmlGlossary1Data += '    <body style=\"background-color: #fafafa;\">';
xmlGlossary1Data += '        <div id=\"GlossaryBody\">';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_0\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Full-text Search</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor1\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_0\" style=\"display: none;\">The ability to search an entire Help system for a particular word or keyword.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_1\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Hard disk capacity</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor2\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_1\" style=\"display: none;\">The amount of memory available on a PC fixed media storage device, usually measured in Mega (million) bytes (Mb) of memory.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_2\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">HTML</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor3\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_2\" style=\"display: none;\">Hypertext Markup Language. A set of tags used to mark the structural elements of text files. HTML files include tags that create hyperlinks to other documents on the Internet.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_3\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">HTTP</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor4\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_3\" style=\"display: none;\">Hypertext Transfer Protocol. The communications protocol on which the Web is based. HTTP sets rules for how information is passed between the server and the browser software.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_4\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Icon</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor5\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_4\" style=\"display: none;\">A picture or symbol that represents an object, task, command, or choice users can select by pointing and clicking with a mouse.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_5\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Index</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor6\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_5\" style=\"display: none;\">A list of keywords the user may view to find topics within a Help system.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_6\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Memory</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor7\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_6\" style=\"display: none;\">The part of a computer that stores information or instructions. Memory can be RAM (Random Access Memory) or ROM (Read Only Memory), and is usually measured in Kilobytes (thousand) or Megabytes (million) bytes of memory.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_7\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Newsgroup</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor8\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_7\" style=\"display: none;\">A collection of messages posted by individuals to a news server (a computer maintained by a company, group, or individual). Newsgroups exist on practically every subject. Messages can be posted and read by anyone who has access to that group.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_8\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Page</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor9\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_8\" style=\"display: none;\">An individual topic within a Help system.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_9\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Pane</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor10\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_9\" style=\"display: none;\">A frame used to display program components.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_10\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Tour</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor11\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_10\" style=\"display: none;\">Screen shots and information about a product displayed in sequential order. Designed for a user who wants to walk through a feature or a program.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_11\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">URL</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor12\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_11\" style=\"display: none;\">Uniform Resource Locator. An Internet address, as well as a standard method of naming files on the Web. A URL begins with a protocol name (such as http), followed by a colon and two forward slashes(//). Next comes the name of the internet server that the file is stored on, followed by directories that hold the file, separated by forward slashes(/). The filename comes last, as shown in the following example:  http://www.mycompany.com/whatsnew.htm</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_12\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">Web browser</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor13\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_12\" style=\"display: none;\">Commonly called a browser. A software application for displaying HTML pages on the World Wide Web. Common browser applications include Microsoft Internet Explorer and Netscape Navigator.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_13\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">WWW</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor14\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_13\" style=\"display: none;\">World Wide Web. The graphical Internet hypertext service that uses the HTTP protocol to retrieve Web pages and other resources from Web servers.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '            <div class=\"GlossaryPageEntry\">';
xmlGlossary1Data += '                <div class=\"GlossaryPageTerm\">';
xmlGlossary1Data += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_437653829_14\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">WYSIWYG</a>';
xmlGlossary1Data += '                    <a name=\"437653829_anchor15\">';
xmlGlossary1Data += '                    </a>';
xmlGlossary1Data += '                </div>';
xmlGlossary1Data += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_437653829_14\" style=\"display: none;\">(What You See Is What You Get). A development option that allows you to view items in the editor as they will display for end-users.</div>';
xmlGlossary1Data += '            </div>';
xmlGlossary1Data += '        </div>';
xmlGlossary1Data += '        <p>&#160;</p>';
xmlGlossary1Data += '        <script type=\"text/javascript\" src=\"SkinSupport/MadCapBodyEnd.js\">';
xmlGlossary1Data += '        </script>';
xmlGlossary1Data += '    </body>';
xmlGlossary1Data += '</html>';
CMCXmlParser._FilePathToXmlStringMap.Add('Glossary1', xmlGlossary1Data);
